on:
  push:
    branches:
      - main
      - gh-actions-test
    tags:
      - generate-docs
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Doxygen on GitHub Pages
        id: ghaction
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
          doxyfile-path: Doxyfile
          html-output-folder: Docs/Doxygen/html
          branch: gh-pages